### ISSUE TITLE
Cocaine is unserializable

### ISSUE THREAD

**Issue by ghost** [areinfranck/DrugsPlugin#2]
Hello! I was using Drugs 5.1 when I noticed that AngelChest was failing to place chests. After some investigation, we found that the Cocaine item was causing issues with CraftBukkit enchantments, leading to errors in writing the files. I believe this to be the result of the drugs:glow enchantment.

**Comment by mfnalex** [comment]
Hi, I'm the author of AngelChest. I looked into the issue and it is definitely an issue on Drugs' side: the ItemStack cannot be serialized, it cannot even be turned #toString.

Here's a simple plugin to 100% reproduce the issue:

```java
package de.jeff_media.printcurrentitem;

import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;

public class PrintCurrentItem extends JavaPlugin {

    @Override
    public void onEnable() {
        getCommand("print").setExecutor(this);
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if(sender instanceof Player) {
            ItemStack mainHand = ((Player)sender).getInventory().getItemInMainHand();
            sender.sendMessage("Item: " + mainHand);
        }
        return true;
    }
}
```

When holding a normal ItemStack, the command above works fine:

![image](https://user-images.githubusercontent.com/1122571/127102878-1159f1b1-3546-4703-8891-fe3c50442158.png)

When doing the same command holding cocaine, the console begins to cry:

![image](https://user-images.githubusercontent.com/1122571/127102959-1b0810e3-8141-4aea-bd69-950387eb932e.png)

```
[07:55:10 INFO]: mfnalex issued server command: /print
[07:55:10 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'print' in plugin PrintCurrentItem v1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-782]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: null key in entry: null=1
        at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32) ~[patched_1.16.5.jar:git-Paper-782]
        at com.google.common.collect.ImmutableMapEntry.<init>(ImmutableMapEntry.java:49) ~[patched_1.16.5.jar:git-Paper-782]
        at com.google.common.collect.ImmutableMap.entryOf(ImmutableMap.java:172) ~[patched_1.16.5.jar:git-Paper-782]
        at com.google.common.collect.ImmutableMap$Builder.put(ImmutableMap.java:248) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serializeEnchantments(CraftMetaItem.java:1504) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1426) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.serialize(CraftMetaItem.java:1402) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftMetaItem.toString(CraftMetaItem.java:1574) ~[patched_1.16.5.jar:git-Paper-782]
        at java.lang.String.valueOf(String.java:3365) ~[?:?]
        at java.lang.StringBuilder.append(StringBuilder.java:169) ~[?:?]
        at org.bukkit.inventory.ItemStack.toString(ItemStack.java:258) ~[patched_1.16.5.jar:git-Paper-782]
        at java.lang.String.valueOf(String.java:3365) ~[?:?]
        at java.lang.StringBuilder.append(StringBuilder.java:169) ~[?:?]
        at de.jeff_media.printcurrentitem.PrintCurrentItem.onCommand(PrintCurrentItem.java:20) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-782]
        ... 19 more
```

Tested on Paper 1.16.5 #782 and Paper 1.17.1 #92

**Comment by mfnalex** [comment]
Note: the error message from above is a clean paper 1.16.5 #782 server with NOTHING installed besides Drugs and the above mentioned testing plugin

**Comment by areinfranck** [comment]
Hello, thanks for using the plugin! Kirby is correct in that the issue lied in the [Glow.java](https://github.com/TheMindDroid/DrugsPlugin/blob/main/src/main/java/me/theminddroid/drugs/models/Glow.java#L39-L43) class. The glowing effect was meant solely to be a visual element to make the drugs look different from the base items. In order to do so, I added a "fake" enchantment effect, which returned null for the enchantment type as the item is technically not enchanted. This however threw an exception when your plugin tried to turn that null enchantment name into a string from its item stack.

I edited the code so it now returns a string called "Drug", resolving the issue you posed. Bear in mind that this is still not the name of a real Minecraft enchantment, so you won't be able to do anything with it.


Previous code:
```java
@Override
    public String getName() {
        // TODO Auto-generated method stub
        return null;
    }
```

Working Change:
```java
@Override
    public String getName() {
        // TODO Auto-generated method stub
        return "Drug";
    }
```

Here's a screenshot of what the new item stack should look like:

![Cocaine](https://user-images.githubusercontent.com/62492700/127266801-3a3b9ac7-a8df-4591-af93-5df34fa89d04.png)

Please go ahead and give the attached plugin a test to make sure everything works. If all is good, I'll publish this version in the event that others encounter the same issue. If issues persist, I'll do what I can to fix them.

[Drugs-5.2.zip](https://github.com/TheMindDroid/DrugsPlugin/files/6890472/Drugs-5.2.zip)

Thanks for the feedback!

**Comment by mfnalex** [comment]
I'll check it out right now :)

**Comment by mfnalex** [comment]
Yep, this is fixed in the .jar you sent!

**Comment by ghost** [comment]
The changes in the 5.2 version fix the issue. Thanks! :)

**Comment by mfnalex** [comment]
BTW the title of this issue made my day lol. "Cocaine is unserializable" - maybe my dealer will give me a discount when I complain about this fact?

**Comment by areinfranck** [comment]
Awesome, glad I could help!
